name: Build and deploy Node.js app to Azure Web App - aifl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install --prefix client

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV
        
      - name: Build React app
        run: npm run build --prefix client

      - name: Move React build to server public directory
        run: xcopy /E /I client\build server\public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production' # or your environment name
      url: ${{ steps.deploy-server.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aifl' # Set your app name here
          slot-name: 'production' # If you're using a deployment slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Set your Azure publish profile secret here
          package: .
