name: Build and deploy Node.js app to Azure Web App - aifl

on:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        run: npm install

      - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-server
        path: .

  deploy-server:
    runs-on: windows-latest
    needs: build-server

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-server

    steps:
      - name: Deploy server to Azure
        run: |
          node server.js
       

 