name: Build and deploy Node.js app to Azure Web App - aifl

on:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        run: npm install

  deploy-server:
    runs-on: windows-latest
    needs: build-server

    steps:
      - name: Deploy server to Azure
        run: |
          node server.js
       

  build-client:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for React app
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build React app
        run: |
          cd client
          npm run build

  deploy-client:
    runs-on: windows-latest
    needs: build-client

    steps:
      - name: Deploy client to Azure
        run: |
          # Deploy the React app to Azure using your preferred deployment method.


